 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var multer  = require('multer')
var storage = multer.memoryStorage()
var upload = multer({ storage: storage })

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })


app.post('/', upload.single('upl'), function(req, res, next){
  res.json({size: req.file.size});
})


app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

