 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var multer  = require('multer')
var storage = multer.memoryStorage()
var upload = multer({ storage: storage })

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })


app.post('/file-upload', upload.single('file'), function(req, res, next){
  console.log(req.file.length)
  res.send();
})


app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

